# Generated by Django 5.2.8 on 2025-11-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
