# Generated by Django 5.2.8 on 2025-11-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_password_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='user',
        ),
    ]
